### PR TITLE
Reflect 1.0.0 rc1 and  Replace obsolete function in Webform 6.0 for Drupal 9 

### PR DESCRIPTION
**Pull request by giancarlobi**
# What is this?
Webform 6.0 removed a function (was marked as obsolete in 5.x but this moved so fast!). This pull syncs some older beta3 and replaces the call with the current function. Some of this will be overriden when ISSUE-60 gets merged but for now this should deploying on Drupal 9 no longer an act of faith 😆 

Thanks @giancarlobi

### CODE REVIEW

**Comment by DiegoPino** [comment]
@giancarlobi thanks. Looking at this pull it brings a mixed set of commits from ISSUE-60 and some olders so a squash would not be good idea but then it will have some empty ones too. Maybe i should simply merge ISSUE-60 into 1.0.0RC1? What do you think? Let me check my ISSUE-60 to see if anything is missing there

**Comment by giancarlobi** [comment]
@DiegoPino this PR only affects composer.json and function replacement. Other entries are duties due to fork and PR from my git.

**Comment by DiegoPino** [comment]
Yes, i just fear duplication because i need to squash to make all the fork/rebase/duties disappear from the main branch once merged.  And e.g https://github.com/esmero/webform_strawberryfield/pull/65/commits/d1ee7cf959eccec7707e3c470f8ac6a619d86cd6 is already in ISSUE-60 with a different approach. Well, its also Ok. I prefer to test ISSUE-60 before merging to fast so let's move on with this!

**Comment by DiegoPino** [comment]
@giancarlobi done, all 3x merged.

**Pull request merged**
