### PR TITLE
ISSU-119: Validate/Clean non valid UTF-8 CSV data imports via webform elements

### PR DESCRIPTION
**Pull request by DiegoPino**
See #119 

Adds a new Option for the Metadata CSV upload element. If checked, CSVs with invalid UTF-8 characters will be validated/rejected at the Form Element level. If not, we will still do sanity/clean and checks

Finally added some Visual/UI/Logs help in case something weird happens with the data we have no control over during a Webform ingest. Should not happen since this is the only Element Family that injects data directly into the SBF JSON and this is NOW! solved. But maybe someone ends doing data magic in the future too.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@patdunlavey @giancarlobi if any of you could give this a quick visual pass and see if anything here makes noise/looks weird for you, I would be thankful. I tested this and it is working but good to have your wisdom and experience detecting outer space bugs here. Thanks!

**Comment by patdunlavey** [comment]
Hi @DiegoPino visual looks good to me. I'm impressed with your economy of code, which makes it reasonably easy to to follow what's going on, and to be pretty confident that regressions are not being introduced.

Do you want me to do some testing? If so, perhaps more expansive testing instructions would be helpful.

**Comment by DiegoPino** [comment]
@patdunlavey thanks a lot (and thanks for your kind words). I will do some extra cleanup (saw a DCS issue) and then follow up with a set of example CSVs. I really appreciate your quick response on this, Gold medal for you 🥇

**Comment by DiegoPino** [comment]
Merging into RC3. Thanks.

**Pull request merged**
