### PR TITLE
webform_options_twig: added twig extensions for webform options label rendering

### PR DESCRIPTION
**Pull request by patdunlavey**
# WIP/DRAFT
I'm just creating this PR to get feedback. It may turn into a real PR.
See https://github.com/esmero/webform_strawberryfield/pull/99
and https://github.com/esmero/webform_strawberryfield/issues/96

# What?
Creates two twig extensions for webform select lists so that when a value is stored in the json, we can use twig to render the label corresponding to that value. 

- `sbf_webform_select_element_option_label` will work for any value saved by a webform select widget. It takes as arguments, the machine name of the webform and the machine name of the element in the webform, and the value. It loads the webform, then loads the element, then looks for the value in the element's `#options` list  and returns the label corresponding to it. 
- `sbf_webform_option_label` requires knowing what webform options entity was used to provide the value/label pair. It takes as arguments the machine name for the webform options list, and the value. It loads the options list, looks for the value in that list, and returns the label if it is found.

# To Test
- Create a webform with some select list elements that will save their value(s) to an ADO strawberryfield json.
- Create and test a metadata display with twig to convert the values to labels. Example:
```
{{ sbf_webform_select_element_option_label('testing_value_label_element', 'test_select', data.test_select) }}
{{ sbf_webform_option_label('languages_iso_639_2', data.test_select) }}
```

### CODE REVIEW

**Comment by patdunlavey** [comment]
@DiegoPino My thinking in putting this into the webform_strawberryfield module is that it's tied to the fact that the values stored come from webform select lists, not general strawberryfield json. That seemed to make more sense to me than putting it into format_strawberryfield, even though it's about rendering metadata. If, hypothetically speaking, we came up with a new module that provides a unique kind of value/label source into strawberryfield json, my thinking is that it's that modules obligation to account for how it might be displayed (and indexed in solr, though that's another discussion). It doesn't make sense to me that format_strawberryfield should have to keep up with what's coming in from other modules.

**Comment by DiegoPino** [comment]
I agree. This fits better in this module.

Question. 
```PHP
{{ bamboo_config_get('schema_org_creative_works', 'options') }}
````
Loads the config and gives you back the options. It does not do exactly the same (I agree), still I lose nothing asking, did you try with that one already and it did not work?


Also side note:

check 

https://github.com/esmero/webform_strawberryfield/blob/58d58e6499c6cb11c08c8758fcaaf649914f5686/webform_strawberryfield.module#L562-L583


I'm already pushing for the last used Webform to feed the SBF all elements flatten (yeah, its a lot but hey, maybe there is a use case like getting each JSON key equivalent in the webform label). Is there any data in that you can use too?

In any case I'm ok with the idea of these extension!

**Comment by patdunlavey** [comment]
I was not familiar with `bamboo_config_get`, so maybe the second twig extension, `sbf_webform_option_label`, is not needed. However, the first one, `sbf_webform_select_element_option_label`, in theory, handles any kind of webform select list, not just those provided by webform_options configuration entities. Is there some other already existing way to deal with that need?

Do you think hook_format_strawberryfield_twigcontext_alter() is a better way to handle this?  I'm thinking not, since it would presumably fetch select list labels for *all* select elements, whether they're needed or not (usually, they are not actually needed). However it would have the advantage of making writing twig templates easier.

@DiegoPino this PR only addresses one part of the need, and I don't want to lose sight of the fact that we also need to have a corresponding functionality on the solr indexing side. I spent a little while trying to understand how I might make a strawberryfield key name provider plugin to index labels when provided a select list value, but quickly got lost. If, when you have a moment (ha!) you could provide a bit of an orientation on how I might do that, that would be greatly appreciated!

**Comment by DiegoPino** [comment]
@patdunlavey I'm ok with having both of your extension @patdunlavey. The bamboo one may be a good example for certain things but having a more specific one feels better so go ahead. Maybe you and I can have a chat/quality time exploring your use cases and figure out the full pipeline? From ingest to index to render back? let me know if that works (can be a 30 minutes, call you talking, me listening)

**Comment by patdunlavey** [comment]
Thanks very much for your time/consideration of this @DiegoPino. On reflection, this seems like it makes more sense as something for a custom module rather than in the webform_strawberryfield. I'm going to close this PR in favor of implementing the twig extensions in a separate module. If you disagree, please re-open!

**Pull request closed without merging**
