### PR TITLE
ISSUE-115: make missing index 'data-drupal-date-format' notice go away

### PR DESCRIPTION
**Pull request by patdunlavey**
Not sure if this is a correct solution, but everything seems to work fine with this change.

@DiegoPino

### CODE REVIEW

**Comment by DiegoPino** [comment]
@patdunlavey thanks a lot!
Could you double check this line too?

https://github.com/esmero/webform_strawberryfield/blob/680270b3bda51832b5170e4a43255158f5ccd214/src/Plugin/WebformElement/WebformMetadataDate.php#L99-L106

The failed logic is that "if Date Picker" is enabled then that attribute needs to be set. So if its not set (and your correction is perfect) should we also "disable Date Picker?" Or said different, is your Date Picker disabled and its still showing?

**Comment by patdunlavey** [comment]
Will do!

**Comment by DiegoPino** [comment]
Thanks @patdunlavey !

**Comment by patdunlavey** [comment]
@DiegoPino here's how I have the date field configured:
```yml
date_test:
  '#type': metadata_date
  '#title': 'Date Test'
  '#multiple': true
  '#title_display': before
  '#required': true
  '#date_date_format': ''
```
I messed around with the datepicker checkboxes, and form some reason was not able to get consistent behavior. Initially, the date_free field was showing the date picker button regardless of the datepicker settings. Later, after messing around, with enabling the two checkboxes, and with trying out some conditional logic, and finally returning everything to its original state, this time the date_free field would not show the datepicker button! On the other hand, also I did not see that these settings had any impact on the date picker behavior for the date_from and date_to fields.
All that said, I don't think the date-picker problem, if indeed there is one, needs to be resolved before accepting this PR.

**Review by DiegoPino — APPROVED** [review]
Simple good fix. Thanks!

**Comment by DiegoPino** [comment]
Ok, let's roll with this commit first. I can deal with Date Picker afterwards. Thanks @patdunlavey

**Pull request merged**
